repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-comprehensions==3.3.0
        -   flake8-eradicate==1.0.0
        -   flake8-quotes==3.2.0
        -   flake8-unused-arguments==0.0.6
        -   flake8-builtins==1.5.2
        -   flake8-print==3.1.4
